# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  ğŸ‘‹ Thanks for opening your first issue here! 
  If you're reporting a ğŸ bug, please make sure you include steps to reproduce it - this will help us to resolve it more quickly. 

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines.

  ğŸ’– Thanks for opening this pull request! ğŸ’–
  Things that will help get your PR across the finish line:
  - Run `make check` locally to catch any obvious errors.
  - Document any user-facing changes you've made, including ChangeLog.md.
   - Include tests when adding/changing behavior.
  - Include screenshots and animated GIFs whenever possible.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ğŸ‰ğŸ‰
  Thanks for helping to improve the project!

