language: go

sudo: false

go:
  - "1.10"

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - make install-linters

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
  
script:
  - make check
  - $GOPATH/bin/goveralls -service=travis-ci

after_success:
  - bash <(curl -s https://codecov.io/bash)