# Wing Commander example configuration file
# Use this file as a tempate to build your own configuration file
# and place it in ~/.wingcommander/config.toml
# Default values are commented out

# Telegram configuration
[telegram]
# Telegram bot API key (token). This is provided by the @BotFather. The value must be enclosed in " "
apikey = "BOT-APIKEY-HERE"
# Telegram chatid. Go here to find this: https://api.telegram.org/bot<YourBOTToken>/getUpdates
# This is an integer field - not a string - dont use " "
chatid = 123456789
# Your Telegram @USERNAME enclosed in " "
admin = "@USERNAME"
# Telegram API debugging (true or false)
#debug = false

# Skyminer monitor configuration
# These configurations are used once monitoring is started 
[monitor]
# Skyminer polling interval (in seconds). Controls how often the bot will 
# talk to the Skyminer.
#intervalsec = 10

# Bot heartbeat interval (in minutes). Default is 120min (2hrs).
# Controls the interval that the bot will automatically provide any update
# via Telegram. This is active once monitoring has started.
#heartbeatintmin = 120

# Skyminer Manager configuration
[skymanager]
# IP:PORT for where the Skyminer Manager node is located.
# The bot can be run on a seperate machine to the Manager, but by default
# it is assumed it will be running on the same machine and that the 
# Skywire Manager app defaults are in use
#address="127.0.0.1:8000"

# Skycoin Skywire Discovery Node address
#discoveryaddress="discovery.skycoin.net:8001"
